// Forum verileri
const forumData = {
  categories: [
    { id: 1, title: "Genel Tartışma", description: "Genel konuların tartışıldığı bölüm.", lastActive: "Az önce" },
    { id: 2, title: "Teoloji", description: "Teoloji ile ilgili konuların tartışıldığı bölüm.", lastActive: "Dün" },
    {
      id: 3,
      title: "Felsefe",
      description: "Felsefe ile ilgili konuların tartışıldığı bölüm.",
      lastActive: "2 gün önce",
    },
    {
      id: 4,
      title: "Teknoloji",
      description: "Teknoloji ile ilgili konuların tartışıldığı bölüm.",
      lastActive: "3 gün önce",
    },
    { id: 5, title: "Spor", description: "Spor ile ilgili konuların tartışıldığı bölüm.", lastActive: "4 gün önce" },
  ],
  topics: [
    {
      id: 1,
      categoryId: 1,
      title: "Forum Kuralları",
      author: "Admin",
      authorRole: "Yönetici",
      date: "1 Ocak 2023",
      views: 150,
      content: "Lütfen forum kurallarına uyun.",
      likes: 10,
    },
    {
      id: 2,
      categoryId: 2,
      title: "Teoloji Tartışması",
      author: "YeniUye",
      authorRole: "Üye",
      date: "2 Ocak 2023",
      views: 50,
      content: "Teoloji hakkında düşünceleriniz nelerdir?",
      likes: 5,
    },
    {
      id: 3,
      categoryId: 3,
      title: "Felsefe Soruları",
      author: "Filozof",
      authorRole: "Üye",
      date: "3 Ocak 2023",
      views: 75,
      content: "Felsefe hakkında sorularınız var mı?",
      likes: 8,
    },
    {
      id: 4,
      categoryId: 4,
      title: "Yeni Teknolojiler",
      author: "TechGuru",
      authorRole: "Üye",
      date: "4 Ocak 2023",
      views: 100,
      content: "Yeni teknolojiler hakkında ne düşünüyorsunuz?",
      likes: 12,
    },
    {
      id: 5,
      categoryId: 5,
      title: "Spor Haberleri",
      author: "SporSever",
      authorRole: "Üye",
      date: "5 Ocak 2023",
      views: 120,
      content: "Son spor haberleri hakkında konuşalım.",
      likes: 15,
    },
  ],
  replies: [
    {
      id: 1,
      topicId: 1,
      author: "Uye1",
      authorRole: "Üye",
      date: "1 Ocak 2023",
      content: "Anladım, teşekkürler!",
      likes: 2,
    },
    {
      id: 2,
      topicId: 2,
      author: "Uye2",
      authorRole: "Üye",
      date: "3 Ocak 2023",
      content: "Çok ilginç bir konu!",
      likes: 3,
    },
    {
      id: 3,
      topicId: 3,
      author: "Uye3",
      authorRole: "Üye",
      date: "4 Ocak 2023",
      content: "Felsefe hakkında daha fazla bilgi paylaşabilir misiniz?",
      likes: 4,
    },
    {
      id: 4,
      topicId: 4,
      author: "Uye4",
      authorRole: "Üye",
      date: "5 Ocak 2023",
      content: "Yapay zeka hakkında ne düşünüyorsunuz?",
      likes: 5,
    },
    {
      id: 5,
      topicId: 5,
      author: "Uye5",
      authorRole: "Üye",
      date: "6 Ocak 2023",
      content: "Son maçı izlediniz mi?",
      likes: 6,
    },
  ],
  members: [
    { id: 1, username: "Admin", role: "Yönetici", isOnline: true, joinDate: "1 Ocak 2023", posts: 25, topics: 10 },
    { id: 2, username: "Uye1", role: "Üye", isOnline: false, joinDate: "2 Ocak 2023", posts: 15, topics: 5 },
    { id: 3, username: "Uye2", role: "Üye", isOnline: true, joinDate: "3 Ocak 2023", posts: 10, topics: 3 },
    { id: 4, username: "Uye3", role: "Üye", isOnline: false, joinDate: "4 Ocak 2023", posts: 8, topics: 2 },
    { id: 5, username: "Uye4", role: "Üye", isOnline: true, joinDate: "5 Ocak 2023", posts: 5, topics: 1 },
    { id: 6, username: "Uye5", role: "Üye", isOnline: false, joinDate: "6 Ocak 2023", posts: 3, topics: 0 },
    { id: 7, username: "Moderatör", role: "Moderatör", isOnline: true, joinDate: "7 Ocak 2023", posts: 20, topics: 8 },
    { id: 8, username: "YeniUye", role: "Üye", isOnline: true, joinDate: "8 Ocak 2023", posts: 2, topics: 1 },
    { id: 9, username: "Filozof", role: "Üye", isOnline: false, joinDate: "9 Ocak 2023", posts: 12, topics: 4 },
    { id: 10, username: "TechGuru", role: "Üye", isOnline: true, joinDate: "10 Ocak 2023", posts: 18, topics: 6 },
    { id: 11, username: "SporSever", role: "Üye", isOnline: false, joinDate: "11 Ocak 2023", posts: 7, topics: 2 },
  ],
}

// LocalStorage'a kaydet (ilk kez)
if (!localStorage.getItem("forumData")) {
  localStorage.setItem("forumData", JSON.stringify(forumData))
}

